// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
// RWTexture2D<float4> Result;
RWStructuredBuffer<float> Result;
float positionX;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID) {
  // TODO: insert actual code here!
  Result[0] = positionX + 0.01;

}
